{
 "title": "TSM",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"tsm\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unavailable Volumes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tsm_volumes_unavailable{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Readonly Volumes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tsm_volumes_readonly{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Log Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(tsm_active_log_used_bytes{instance=~\"$instance\"}) by (dbname)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(tsm_active_log_free_bytes{instance=~\"$instance\"}) by (dbname)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(tsm_active_log_total_bytes{instance=~\"$instance\"}) by (dbname)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Scratch Tapes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(tsm_libvolume_media{status=\"scratch\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Drives Offline",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(tsm_drive_online{instance=~\"$instance\"}) - sum(tsm_drive_online{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "DB TSMDB1 Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(tsm_db_space_used_bytes{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(tsm_db_space_free_bytes{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(tsm_db_space_total_bytes{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB TSMDB1 Page Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Pages" }
   ],
   "targets": [
    {
     "expr": "sum(tsm_db_pages_used{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(tsm_db_pages_free{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Free"
    },
    {
     "expr": "sum(tsm_db_pages_total{instance=~\"$instance\",dbname=\"TSMDB1\"}) by (dbname)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Schedule Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "tsm_schedule_duration_seconds", "legendFormat": "{{schedule}}" }
   ]
  },
  {
   "title": "Replication Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "tsm_replication_duration_seconds",
     "legendFormat": "{{nodename}} - {{fsname}}"
    }
   ]
  },
  {
   "title": "Replicated Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tsm_replication_replicated_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{nodename }} - {{fsname}}"
    }
   ]
  },
  {
   "title": "Replicated Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tsm_replication_replicated_files{instance=~\"$instance\"}",
     "legendFormat": "{{nodename }} - {{fsname}}"
    }
   ]
  }
 ]
}